baseURL = 'https://jsan.ch/'
languageCode = 'en-uk'
title = "Jacob Sánchez"
theme = "hello-friend-ng"
paginate = 10
googleAnalytics = 'G-VKHKD5MKMY'

contentDir  = "content"
publishDir  = "public"
dataDir     = "data"
archetypeDir = "archetypes"

[permalinks]
  posts = "/posts/:year/:month/:title/"

[params]
  dateform = "Jan 2, 2006"
  dateformShort = "Jan 2"
  dateformNum = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Software developer"

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Enable theme toggling
  enableThemeToggle = true

  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "My personal website about software and computers"
  keywords = "homepage, blog, tech, software, computers, development"
  images = [""]

[params.author]
  name = "Jacob Sánchez"

[taxonomies]
  category = "categories"
  tag      = "tags"
  series   = "series"

[languages]
  [languages.en.params]
    title = "I am Jacob"
    subtitle = "follow me and get in touch"
    keywords = "blog,tech,software"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "cd /"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

[menu]
  # And you can even create generic menu
  [[menu.main]]
    identifier = "wearemagic"
    name       = "WeAreMagic"
    url        = "https://github.com/magicweare"
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"

# Social Icons

[[params.social]]
  name = "github"
  url = "https://github.com/sanjacob"

[[params.social]]
  name = "twitter"
  url = "https://twitter.com/jacobszpz"

[[params.social]]
  name = "linkedin"
  url = "https://linkedin.com/in/sanjacob"

